name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]
  workflow_dispatch:

jobs:
  # ============================================================
  # Job 1: Code Quality & Linting
  # ============================================================
  code-quality:
    name: Code Quality Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black isort flake8 mypy
      
      - name: Check Code Formatting (Black)
        run: black --check hb_eval/
      
      - name: Check Import Sorting (isort)
        run: isort --check-only hb_eval/
      
      - name: Lint Code (Flake8)
        run: flake8 hb_eval/ --max-line-length=100 --extend-ignore=E203,W503

  # ============================================================
  # Job 2: Test Suite (Multiple Python Versions)
  # ============================================================
  test:
    name: Test Suite (Python ${{ matrix.python-version }})
    runs-on: ${{ matrix.os }}
    
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.8', '3.9', '3.10', '3.11', '3.12']
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      - name: Install Package
        run: |
          python -m pip install --upgrade pip
          pip install -e ".[dev]"
      
      - name: Run Tests
        run: |
          pytest tests/ -v --cov=hb_eval --cov-report=xml --cov-report=term
      
      - name: Upload Coverage
        if: matrix.python-version == '3.11' && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v4
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-hb-eval

  # ============================================================
  # Job 3: Demo Execution Test
  # ============================================================
  demo-test:
    name: Demo Execution Test
    runs-on: ubuntu-latest
    needs: [code-quality]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install Package
        run: |
          python -m pip install --upgrade pip
          pip install -e .
      
      - name: Run Demo (Non-Interactive)
        run: |
          echo "Running HB-Eval System Demo..."
          python -c "from hb_eval.demo import setup_demo_environment, seed_initial_experience, demo_1_retrieval, demo_2_generation; edm, planner, agent = setup_demo_environment(); seed_initial_experience(edm); demo_1_retrieval(agent); demo_2_generation(agent); print('Demo completed successfully!')"

  # ============================================================
  # Job 4: Docker Build Test
  # ============================================================
  docker-build:
    name: Docker Build Test
    runs-on: ubuntu-latest
    needs: [test]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build Docker Image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: hb-eval-system:test
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Test Docker Image
        run: |
          docker run --rm hb-eval-system:test python -c "import hb_eval; print('Docker image works!')"

  # ============================================================
  # Job 5: Security Scan
  # ============================================================
  security-scan:
    name: Security Vulnerability Scan
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Safety
        run: pip install safety
      
      - name: Run Safety Check
        run: safety check --json || true
      
      - name: Run Bandit Security Linter
        run: |
          pip install bandit
          bandit -r hb_eval/ -f json -o bandit-report.json || true

  # ============================================================
  # Job 6: Build Package
  # ============================================================
  build-package:
    name: Build Python Package
    runs-on: ubuntu-latest
    needs: [test, demo-test]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install Build Tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine
      
      - name: Build Package
        run: python -m build
      
      - name: Check Package
        run: twine check dist/*
      
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist-packages
          path: dist/

  # ============================================================
  # Job 7: Success Notification
  # ============================================================
  all-tests-passed:
    name: All Tests Passed ✅
    runs-on: ubuntu-latest
    needs: [code-quality, test, demo-test, docker-build, build-package]
    
    steps:
      - name: Success Message
        run: |
          echo "============================================"
          echo "✅ All CI/CD checks passed successfully!"
          echo "============================================"